name: ${pluginName}
version: ${version}
author: Longboyy
description: ${description}
main: com.github.longboyy.evolution.Evolution
api-version: ${api_version}
depend: [CivModCore]
permissions:
  evo.op:
    default: op
